/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BgRouteImport } from './routes/bg'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as LocaleRedeemRouteImport } from './routes/$locale/redeem'
import { Route as LocaleLabRouteImport } from './routes/$locale/lab'
import { Route as LocaleCommunityRouteImport } from './routes/$locale/community'
import { Route as LocaleCampusLeaderRouteImport } from './routes/$locale/campus-leader'

const BgRoute = BgRouteImport.update({
  id: '/bg',
  path: '/bg',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRedeemRoute = LocaleRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLabRoute = LocaleLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCommunityRoute = LocaleCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCampusLeaderRoute = LocaleCampusLeaderRouteImport.update({
  id: '/campus-leader',
  path: '/campus-leader',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/bg': typeof BgRoute
  '/$locale/campus-leader': typeof LocaleCampusLeaderRoute
  '/$locale/community': typeof LocaleCommunityRoute
  '/$locale/lab': typeof LocaleLabRoute
  '/$locale/redeem': typeof LocaleRedeemRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bg': typeof BgRoute
  '/$locale/campus-leader': typeof LocaleCampusLeaderRoute
  '/$locale/community': typeof LocaleCommunityRoute
  '/$locale/lab': typeof LocaleLabRoute
  '/$locale/redeem': typeof LocaleRedeemRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$locale': typeof LocaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/bg': typeof BgRoute
  '/$locale/campus-leader': typeof LocaleCampusLeaderRoute
  '/$locale/community': typeof LocaleCommunityRoute
  '/$locale/lab': typeof LocaleLabRoute
  '/$locale/redeem': typeof LocaleRedeemRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/bg'
    | '/$locale/campus-leader'
    | '/$locale/community'
    | '/$locale/lab'
    | '/$locale/redeem'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bg'
    | '/$locale/campus-leader'
    | '/$locale/community'
    | '/$locale/lab'
    | '/$locale/redeem'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$locale'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/bg'
    | '/$locale/campus-leader'
    | '/$locale/community'
    | '/$locale/lab'
    | '/$locale/redeem'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  BgRoute: typeof BgRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bg': {
      id: '/bg'
      path: '/bg'
      fullPath: '/bg'
      preLoaderRoute: typeof BgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/redeem': {
      id: '/$locale/redeem'
      path: '/redeem'
      fullPath: '/$locale/redeem'
      preLoaderRoute: typeof LocaleRedeemRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/lab': {
      id: '/$locale/lab'
      path: '/lab'
      fullPath: '/$locale/lab'
      preLoaderRoute: typeof LocaleLabRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/community': {
      id: '/$locale/community'
      path: '/community'
      fullPath: '/$locale/community'
      preLoaderRoute: typeof LocaleCommunityRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/campus-leader': {
      id: '/$locale/campus-leader'
      path: '/campus-leader'
      fullPath: '/$locale/campus-leader'
      preLoaderRoute: typeof LocaleCampusLeaderRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleCampusLeaderRoute: typeof LocaleCampusLeaderRoute
  LocaleCommunityRoute: typeof LocaleCommunityRoute
  LocaleLabRoute: typeof LocaleLabRoute
  LocaleRedeemRoute: typeof LocaleRedeemRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleCampusLeaderRoute: LocaleCampusLeaderRoute,
  LocaleCommunityRoute: LocaleCommunityRoute,
  LocaleLabRoute: LocaleLabRoute,
  LocaleRedeemRoute: LocaleRedeemRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  BgRoute: BgRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
