/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as BgRouteImport } from './routes/bg'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleSplatRouteImport } from './routes/$locale/$'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteCampusLeaderRouteImport } from './routes/_site/campus-leader'
import { Route as SiteCommunityRouteImport } from './routes/_site/community'
import { Route as SiteLabRouteImport } from './routes/_site/lab'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteRedeemRouteImport } from './routes/_site/redeem'
import { Route as SiteTermsRouteImport } from './routes/_site/terms'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SiteApertureJoinRouteImport } from './routes/_site/aperture/join'
import { Route as SiteEventsSlugRouteImport } from './routes/_site/events/$slug'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'
import { Route as ApiWebhooksWompiRouteImport } from './routes/api/webhooks/wompi'
import { Route as SiteEventsSlugIndexRouteImport } from './routes/_site/events/$slug.index'
import { Route as SiteEventsSlugSuccessRouteImport } from './routes/_site/events/$slug.success'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const BgRoute = BgRouteImport.update({
  id: '/bg',
  path: '/bg',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSplatRoute = LocaleSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LocaleRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCampusLeaderRoute = SiteCampusLeaderRouteImport.update({
  id: '/campus-leader',
  path: '/campus-leader',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCommunityRoute = SiteCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLabRoute = SiteLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRedeemRoute = SiteRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteApertureJoinRoute = SiteApertureJoinRouteImport.update({
  id: '/aperture/join',
  path: '/aperture/join',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEventsSlugRoute = SiteEventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksWompiRoute = ApiWebhooksWompiRouteImport.update({
  id: '/api/webhooks/wompi',
  path: '/api/webhooks/wompi',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteEventsSlugIndexRoute = SiteEventsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteEventsSlugRoute,
} as any)
const SiteEventsSlugSuccessRoute = SiteEventsSlugSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => SiteEventsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$locale': typeof LocaleRouteWithChildren
  '/': typeof SiteIndexRoute
  '/bg': typeof BgRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/campus-leader': typeof SiteCampusLeaderRoute
  '/community': typeof SiteCommunityRoute
  '/lab': typeof SiteLabRoute
  '/privacy': typeof SitePrivacyRoute
  '/redeem': typeof SiteRedeemRoute
  '/terms': typeof SiteTermsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$locale/': typeof LocaleIndexRoute
  '/aperture/join': typeof SiteApertureJoinRoute
  '/events/$slug': typeof SiteEventsSlugRouteWithChildren
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/api/webhooks/wompi': typeof ApiWebhooksWompiRoute
  '/events/$slug/success': typeof SiteEventsSlugSuccessRoute
  '/events/$slug/': typeof SiteEventsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/bg': typeof BgRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/campus-leader': typeof SiteCampusLeaderRoute
  '/community': typeof SiteCommunityRoute
  '/lab': typeof SiteLabRoute
  '/privacy': typeof SitePrivacyRoute
  '/redeem': typeof SiteRedeemRoute
  '/terms': typeof SiteTermsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$locale': typeof LocaleIndexRoute
  '/': typeof SiteIndexRoute
  '/aperture/join': typeof SiteApertureJoinRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/api/webhooks/wompi': typeof ApiWebhooksWompiRoute
  '/events/$slug/success': typeof SiteEventsSlugSuccessRoute
  '/events/$slug': typeof SiteEventsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$locale': typeof LocaleRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/bg': typeof BgRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/_site/campus-leader': typeof SiteCampusLeaderRoute
  '/_site/community': typeof SiteCommunityRoute
  '/_site/lab': typeof SiteLabRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/redeem': typeof SiteRedeemRoute
  '/_site/terms': typeof SiteTermsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$locale/': typeof LocaleIndexRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/aperture/join': typeof SiteApertureJoinRoute
  '/_site/events/$slug': typeof SiteEventsSlugRouteWithChildren
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/api/webhooks/wompi': typeof ApiWebhooksWompiRoute
  '/_site/events/$slug/success': typeof SiteEventsSlugSuccessRoute
  '/_site/events/$slug/': typeof SiteEventsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$locale'
    | '/'
    | '/bg'
    | '/$locale/$'
    | '/campus-leader'
    | '/community'
    | '/lab'
    | '/privacy'
    | '/redeem'
    | '/terms'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$locale/'
    | '/aperture/join'
    | '/events/$slug'
    | '/api/webhooks/clerk'
    | '/api/webhooks/wompi'
    | '/events/$slug/success'
    | '/events/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bg'
    | '/$locale/$'
    | '/campus-leader'
    | '/community'
    | '/lab'
    | '/privacy'
    | '/redeem'
    | '/terms'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$locale'
    | '/'
    | '/aperture/join'
    | '/api/webhooks/clerk'
    | '/api/webhooks/wompi'
    | '/events/$slug/success'
    | '/events/$slug'
  id:
    | '__root__'
    | '/$locale'
    | '/_site'
    | '/bg'
    | '/$locale/$'
    | '/_site/campus-leader'
    | '/_site/community'
    | '/_site/lab'
    | '/_site/privacy'
    | '/_site/redeem'
    | '/_site/terms'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$locale/'
    | '/_site/'
    | '/_site/aperture/join'
    | '/_site/events/$slug'
    | '/api/webhooks/clerk'
    | '/api/webhooks/wompi'
    | '/_site/events/$slug/success'
    | '/_site/events/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LocaleRoute: typeof LocaleRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  BgRoute: typeof BgRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
  ApiWebhooksWompiRoute: typeof ApiWebhooksWompiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bg': {
      id: '/bg'
      path: '/bg'
      fullPath: '/bg'
      preLoaderRoute: typeof BgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/$': {
      id: '/$locale/$'
      path: '/$'
      fullPath: '/$locale/$'
      preLoaderRoute: typeof LocaleSplatRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/campus-leader': {
      id: '/_site/campus-leader'
      path: '/campus-leader'
      fullPath: '/campus-leader'
      preLoaderRoute: typeof SiteCampusLeaderRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/community': {
      id: '/_site/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof SiteCommunityRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/lab': {
      id: '/_site/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof SiteLabRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/redeem': {
      id: '/_site/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof SiteRedeemRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/aperture/join': {
      id: '/_site/aperture/join'
      path: '/aperture/join'
      fullPath: '/aperture/join'
      preLoaderRoute: typeof SiteApertureJoinRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/events/$slug': {
      id: '/_site/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof SiteEventsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/wompi': {
      id: '/api/webhooks/wompi'
      path: '/api/webhooks/wompi'
      fullPath: '/api/webhooks/wompi'
      preLoaderRoute: typeof ApiWebhooksWompiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/events/$slug/': {
      id: '/_site/events/$slug/'
      path: '/'
      fullPath: '/events/$slug/'
      preLoaderRoute: typeof SiteEventsSlugIndexRouteImport
      parentRoute: typeof SiteEventsSlugRoute
    }
    '/_site/events/$slug/success': {
      id: '/_site/events/$slug/success'
      path: '/success'
      fullPath: '/events/$slug/success'
      preLoaderRoute: typeof SiteEventsSlugSuccessRouteImport
      parentRoute: typeof SiteEventsSlugRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleSplatRoute: typeof LocaleSplatRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleSplatRoute: LocaleSplatRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface SiteEventsSlugRouteChildren {
  SiteEventsSlugSuccessRoute: typeof SiteEventsSlugSuccessRoute
  SiteEventsSlugIndexRoute: typeof SiteEventsSlugIndexRoute
}

const SiteEventsSlugRouteChildren: SiteEventsSlugRouteChildren = {
  SiteEventsSlugSuccessRoute: SiteEventsSlugSuccessRoute,
  SiteEventsSlugIndexRoute: SiteEventsSlugIndexRoute,
}

const SiteEventsSlugRouteWithChildren = SiteEventsSlugRoute._addFileChildren(
  SiteEventsSlugRouteChildren,
)

interface SiteRouteChildren {
  SiteCampusLeaderRoute: typeof SiteCampusLeaderRoute
  SiteCommunityRoute: typeof SiteCommunityRoute
  SiteLabRoute: typeof SiteLabRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteRedeemRoute: typeof SiteRedeemRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteApertureJoinRoute: typeof SiteApertureJoinRoute
  SiteEventsSlugRoute: typeof SiteEventsSlugRouteWithChildren
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteCampusLeaderRoute: SiteCampusLeaderRoute,
  SiteCommunityRoute: SiteCommunityRoute,
  SiteLabRoute: SiteLabRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteRedeemRoute: SiteRedeemRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteApertureJoinRoute: SiteApertureJoinRoute,
  SiteEventsSlugRoute: SiteEventsSlugRouteWithChildren,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LocaleRoute: LocaleRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  BgRoute: BgRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
  ApiWebhooksWompiRoute: ApiWebhooksWompiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
