/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as BgRouteImport } from './routes/bg'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleSplatRouteImport } from './routes/$locale/$'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteCampusLeaderRouteImport } from './routes/_site/campus-leader'
import { Route as SiteCommunityRouteImport } from './routes/_site/community'
import { Route as SiteLabRouteImport } from './routes/_site/lab'
import { Route as SiteRedeemRouteImport } from './routes/_site/redeem'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const BgRoute = BgRouteImport.update({
  id: '/bg',
  path: '/bg',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSplatRoute = LocaleSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LocaleRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCampusLeaderRoute = SiteCampusLeaderRouteImport.update({
  id: '/campus-leader',
  path: '/campus-leader',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCommunityRoute = SiteCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLabRoute = SiteLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRedeemRoute = SiteRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => SiteRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$locale': typeof LocaleRouteWithChildren
  '/': typeof SiteIndexRoute
  '/bg': typeof BgRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/campus-leader': typeof SiteCampusLeaderRoute
  '/community': typeof SiteCommunityRoute
  '/lab': typeof SiteLabRoute
  '/redeem': typeof SiteRedeemRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/bg': typeof BgRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/campus-leader': typeof SiteCampusLeaderRoute
  '/community': typeof SiteCommunityRoute
  '/lab': typeof SiteLabRoute
  '/redeem': typeof SiteRedeemRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$locale': typeof LocaleIndexRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$locale': typeof LocaleRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/bg': typeof BgRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/_site/campus-leader': typeof SiteCampusLeaderRoute
  '/_site/community': typeof SiteCommunityRoute
  '/_site/lab': typeof SiteLabRoute
  '/_site/redeem': typeof SiteRedeemRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$locale/': typeof LocaleIndexRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$locale'
    | '/'
    | '/bg'
    | '/$locale/$'
    | '/campus-leader'
    | '/community'
    | '/lab'
    | '/redeem'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bg'
    | '/$locale/$'
    | '/campus-leader'
    | '/community'
    | '/lab'
    | '/redeem'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$locale'
    | '/'
  id:
    | '__root__'
    | '/$locale'
    | '/_site'
    | '/bg'
    | '/$locale/$'
    | '/_site/campus-leader'
    | '/_site/community'
    | '/_site/lab'
    | '/_site/redeem'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$locale/'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LocaleRoute: typeof LocaleRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  BgRoute: typeof BgRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bg': {
      id: '/bg'
      path: '/bg'
      fullPath: '/bg'
      preLoaderRoute: typeof BgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/$': {
      id: '/$locale/$'
      path: '/$'
      fullPath: '/$locale/$'
      preLoaderRoute: typeof LocaleSplatRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/campus-leader': {
      id: '/_site/campus-leader'
      path: '/campus-leader'
      fullPath: '/campus-leader'
      preLoaderRoute: typeof SiteCampusLeaderRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/community': {
      id: '/_site/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof SiteCommunityRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/lab': {
      id: '/_site/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof SiteLabRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/redeem': {
      id: '/_site/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof SiteRedeemRouteImport
      parentRoute: typeof SiteRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocaleRouteChildren {
  LocaleSplatRoute: typeof LocaleSplatRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleSplatRoute: LocaleSplatRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface SiteRouteChildren {
  SiteCampusLeaderRoute: typeof SiteCampusLeaderRoute
  SiteCommunityRoute: typeof SiteCommunityRoute
  SiteLabRoute: typeof SiteLabRoute
  SiteRedeemRoute: typeof SiteRedeemRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteCampusLeaderRoute: SiteCampusLeaderRoute,
  SiteCommunityRoute: SiteCommunityRoute,
  SiteLabRoute: SiteLabRoute,
  SiteRedeemRoute: SiteRedeemRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LocaleRoute: LocaleRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  BgRoute: BgRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
